CREATE TABLE ADDRESS(
NAME VARCHAR(20) NOT NULL UNIQUE PRIMARY KEY,
CITY VARCHAR(20) NOT NULL,
STREET VARCHAR(20) NOT NULL,
DISTRICT VARCHAR(20) NOT NULL,
BOF  INTEGER(20) NOT NULL,
ENTRANCE VARCHAR(20)
);