CREATE TABLE PEOPLE(
ID INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
NAME  VARCHAR(20) NOT NULL,
EGN   VARCHAR(10)     NOT NULL UNIQUE PRIMARY KEY,
AGE   INT (3)    NOT NULL,
EMAIL VARCHAR(20) NOT NULL
);